name: CI

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  UnitTest:
    name: Python Unit Test
    uses: uc-cdis/.github/.github/workflows/python_unit_test.yaml@master
    with:
      python-version: '3.9'
      setup-script: 'tests/ci_setup.sh'

  ImageBuildAndPush:
    name: Build Image and Push
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
